# Generated by Django 3.1.5 on 2021-01-27 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamento',
            old_name='Nome',
            new_name='nome',
        ),
    ]
