# Generated by Django 3.1.5 on 2021-01-11 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_auto_20210111_1924'),
        ('documentos', '0002_documento_dono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='dono',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='funcionarios.funcionario'),
            preserve_default=False,
        ),
    ]
